### ISSUE TITLE
Epic Battle Fantasy 5 (432350)

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/Proton#2056]
# Whitelist Request
- Name of the game to be whitelisted: Epic Battle Fantasy 5
- Steam AppID of the game: 432350

## System Information
- GPU: GTX 1050Ti
- Driver/LLVM version: Nvidia 410.73
- Kernel version: 4.19
- Link to full system information report as [Gist](https://gist.github.com/):  https://gist.github.com/liberodark/b09b4b17857325780f8c4b37391ed4e8
- Proton version: 3.7-8

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

**Comment by liberodark** [comment]
Have play 15h on Proton with this game the only bug is after 2h game is slow !
Just restart the game and work great again.

Have test on on Intel HD Graphics 520 / I3 6100 / 8 Go Ram work but on medium / low for play correctly.

PS : Have a official linux build on the game folder is a swf and flashplayer for linux

**Comment by waspennator** [comment]
Game does not work on my le Oled 1tb Deck with Proton Experimental, I see a white flash on the screen for half a second and then it gets stuck until I manually exit the game through the deck menu. A recent protondb review says it happens unless you use a specific proton ge version (7-55) on desktop mode.

[steam-432350.log.txt](https://github.com/ValveSoftware/Proton/files/14399565/steam-432350.log.txt)

**Comment by waspennator** [comment]
Update, launched it in desktop mode and this showed up, so I'm guessing it's a game mode issue. Let me know if you need another log in desktop mode.

![Screenshot_20240226_204104](https://github.com/ValveSoftware/Proton/assets/78768499/ef813020-d9a9-4adc-b3ec-d4bee03e0d1f)

Update 2: setting it to fullscreen in desktop mode makes it show loading text in the top left, but is still frozen on that visually. Game still seems to work though as I can hear the slime death noises if you click around on screen, kinda hard since the screen is visually stuck

**Comment by waspennator** [comment]
Issue is still present on latest steamos update.

Update: Can confirm issue is an OLED exclusive issue, tried it out on my LCD Deck and it had 0 issue rendering the screen in game mode.

![download (1)](https://github.com/ValveSoftware/Proton/assets/78768499/ea73ad98-f8e6-49af-b390-5d43a1865398)

[steam-432350.log.txt](https://github.com/ValveSoftware/Proton/files/14458382/steam-432350.log.txt)

**Comment by waspennator** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/2056#issuecomment-1972607066

Issue has now been resolved as of latest proton Experimental update.

**Comment by waspennator** [comment]
I dunno if something is going on with my sd card or if it's a game mode problem, but im noticing my deck hard crashing and restarting whenever I launch this game in game mode now. I also noticed my SD card name suddenly changes to the file path name, but I dunno if this is related or not.

[steam-432350.log.txt](https://github.com/user-attachments/files/24417254/steam-432350.log.txt)

**Comment by kisak-valve** [comment]
`err:   Presenter: Failed to create Vulkan surface: VK_ERROR_OUT_OF_HOST_MEMORY` hints at the kernel's OOM handler killing Steam or similar and autorestarting the user session instead of a hard crash.

**Comment by waspennator** [comment]
I dunno why it started doing it recently though. Most times it would launch fine without killing steam, even when I have absolutely nothing open.
